# Generated by Django 3.2.4 on 2021-06-14 17:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_alter_profile_friends_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends_list',
        ),
        migrations.AddField(
            model_name='profile',
            name='friend_list',
            field=models.ManyToManyField(blank=True, related_name='friend_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='friend_request',
            field=models.ManyToManyField(blank=True, related_name='friend_request', to=settings.AUTH_USER_MODEL),
        ),
    ]
